### ISSUE TITLE
StartupTest failed

### ISSUE THREAD

**Issue by yu1ro** [lastaflute/lastaflute-example-harbor#1]
StarupTest failed on
- Intellij IDEA 15
- Debian

(domain and service name I select is "tourmalet")

Could you tell me how to run on my environment?

```java
2015-11-06 09:15:29,048 [main] DEBUG (NewProjectCreator@writeFile():329) - ...Writing to /tourmalet/src/main/webapp/error/500.html
2015-11-06 09:15:29,049 [main] DEBUG (NewProjectCreator@writeFile():329) - ...Writing to /tourmalet/src/main/webapp/js/common.js
2015-11-06 09:15:29,055 [main] DEBUG (NewProjectCreator@writeFile():329) - ...Writing to /tourmalet/src/main/webapp/js/jquery-2.1.3.min.js
2015-11-06 09:15:29,058 [main] DEBUG (NewProjectCreator@writeFile():329) - ...Writing to /tourmalet/src/test/java/org/tourmalet/mylasta/TourmaletActionDefTest.java
2015-11-06 09:15:29,063 [main] DEBUG (NewProjectCreator@writeFile():329) - ...Writing to /tourmalet/src/test/java/org/tourmalet/mylasta/TourmaletLastaDocTest.java
2015-11-06 09:15:29,064 [main] DEBUG (NewProjectCreator@writeFile():329) - ...Writing to /tourmalet/src/test/java/org/tourmalet/unit/.gitignore
2015-11-06 09:15:29,065 [main] DEBUG (NewProjectCreator@writeFile():329) - ...Writing to /tourmalet/src/test/java/org/tourmalet/unit/UnitTourmaletTestCase.java
2015-11-06 09:15:29,066 [main] DEBUG (NewProjectCreator@writeFile():329) - ...Writing to /tourmalet/src/test/resources/.gitkeep
2015-11-06 09:15:29,095 [main] DEBUG (TransactionImpl@rollback():353) - Rollback transaction: [FormatId=4360, GlobalId=1446768927952/0, BranchId=]

java.net.ConnectException: 接続を拒否されました

	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
	at org.dbflute.infra.manage.refresh.DfRefreshResourceRequest.openConnect(DfRefreshResourceRequest.java:154)
	at org.dbflute.infra.manage.refresh.DfRefreshResourceRequest.doRefreshResources(DfRefreshResourceRequest.java:107)
	at org.dbflute.infra.manage.refresh.DfRefreshResourceRequest.refreshResources(DfRefreshResourceRequest.java:90)
	at org.docksidestage.startup.StartupTest.refresh(StartupTest.java:43)
	at org.docksidestage.startup.StartupTest.test_startup_actually(StartupTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)


Process finished with exit code 255
```

**Comment by jflute** [comment]
Thanks, yu1ro

Now I fix it, and push it.
The 'refresh' process is for only Eclipse. (Automatically F5)
So the exception should be continued if it's thrown.

```java
protected void refresh(String serviceName) throws IOException {
    try {
        new DfRefreshResourceRequest(Arrays.asList(serviceName), "http://localhost:8386/").refreshResources();
    } catch (RuntimeException continued) {
        log("*Cannot refresh for Eclipse, but no problem so continue: " + continued.getMessage());
    }
}
```

Please, Fetch and Pull and Retry.

**Comment by yu1ro** [comment]
LGTM!
Thanks!
